-- 기본 중국어 단어 시드
insert into chinese_words (chinese, pinyin, korean, category, example, example_pinyin, example_korean) values
  ('你好', 'nǐ hǎo', '안녕하세요', '인사', '你好，很高兴认识你。', 'Nǐ hǎo, hěn gāoxìng rènshí nǐ.', '안녕하세요, 만나서 반갑습니다.'),
  ('再见', 'zài jiàn', '잘가', '인사', '明天再见！', 'Míngtiān zàijiàn!', '내일 또 만나!'),
  ('谢谢', 'xiè xiè', '감사합니다', '인사', '谢谢你的帮助。', 'Xièxiè nǐ de bāngzhù.', '도와주셔서 감사합니다.'),
  ('对不起', 'duì bù qǐ', '죄송합니다', '인사', '对不起，我迟到了。', 'Duìbùqǐ, wǒ chídào le.', '죄송합니다, 늦었습니다.'),
  ('没关系', 'méi guān xì', '괜찮습니다', '인사', null, null, null),
  ('请', 'qǐng', '~해 주세요', '일상', null, null, null),
  ('是', 'shì', '~이다', '일상', null, null, null),
  ('不是', 'bú shì', '아니다', '일상', null, null, null),
  ('我', 'wǒ', '나', '일상', null, null, null),
  ('你', 'nǐ', '너', '일상', null, null, null),
  ('他', 'tā', '그', '일상', null, null, null),
  ('她', 'tā', '그녀', '일상', null, null, null),
  ('吃', 'chī', '먹다', '음식', '我想吃饭。', 'Wǒ xiǎng chīfàn.', '밥 먹고 싶어요.'),
  ('喝', 'hē', '마시다', '음식', null, null, null),
  ('水', 'shuǐ', '물', '음식', null, null, null),
  ('茶', 'chá', '차', '음식', null, null, null),
  ('米饭', 'mǐ fàn', '쌀밥', '음식', null, null, null),
  ('多少钱', 'duō shǎo qián', '얼마예요?', '쇼핑', '这个多少钱？', 'Zhège duōshǎo qián?', '이거 얼마예요?'),
  ('太贵了', 'tài guì le', '너무 비싸요', '쇼핑', null, null, null),
  ('便宜', 'pián yí', '싸다', '쇼핑', null, null, null),
  ('高兴', 'gāo xìng', '기쁘다', '감정', null, null, null),
  ('生气', 'shēng qì', '화나다', '감정', null, null, null),
  ('难过', 'nán guò', '슬프다', '감정', null, null, null),
  ('一', 'yī', '1', '숫자', null, null, null),
  ('二', 'èr', '2', '숫자', null, null, null),
  ('三', 'sān', '3', '숫자', null, null, null),
  ('今天', 'jīn tiān', '오늘', '시간', null, null, null),
  ('明天', 'míng tiān', '내일', '시간', null, null, null),
  ('昨天', 'zuó tiān', '어제', '시간', null, null, null),
  ('学校', 'xué xiào', '학교', '장소', null, null, null),
  ('医院', 'yī yuàn', '병원', '장소', null, null, null),
  ('车站', 'chē zhàn', '정거장', '교통', null, null, null);

-- 기본 이탈리아어 단어 시드
insert into italian_words (italian, pronunciation, korean, category, example, example_pronunciation, example_korean) values
  ('Ciao', '차오', '안녕/잘 가', '인사', 'Ciao! Come stai?', '차오! 꼬메 스따이?', '안녕! 잘 지내?'),
  ('Buongiorno', '부온조르노', '좋은 아침', '인사', 'Buongiorno, signora!', '부온조르노, 씨뇨라!', '좋은 아침이에요, 선생님!'),
  ('Grazie', '그라찌에', '감사합니다', '인사', 'Grazie mille!', '그라찌에 밀레!', '정말 감사합니다!'),
  ('Mi dispiace', '미 디스삐아체', '죄송합니다', '인사', 'Mi dispiace, sono in ritardo.', '미 디스삐아체, 소노 인 리따르도.', '죄송합니다, 늦었습니다.'),
  ('Prego', '쁘레고', '천만에요', '인사', null, null, null),
  ('Per favore', '뻬르 파보레', '~해 주세요', '일상', null, null, null),
  ('Sì', '씨', '네', '일상', null, null, null),
  ('No', '노', '아니오', '일상', null, null, null),
  ('Io', '이오', '나', '일상', null, null, null),
  ('Tu', '뚜', '너', '일상', null, null, null),
  ('Lui', '루이', '그', '일상', null, null, null),
  ('Lei', '레이', '그녀', '일상', null, null, null),
  ('Mangiare', '만쟈레', '먹다', '음식', 'Voglio mangiare la pizza.', '볼료 만쟈레 라 삐짜.', '피자 먹고 싶어요.'),
  ('Bere', '베레', '마시다', '음식', null, null, null),
  ('Acqua', '아꾸아', '물', '음식', null, null, null),
  ('Tè', '떼', '차', '음식', null, null, null),
  ('Riso', '리조', '쌀밥', '음식', null, null, null),
  ('Quanto costa?', '꽌또 코스따?', '얼마예요?', '쇼핑', 'Quanto costa questo?', '꽌또 코스따 꾸에스또?', '이거 얼마예요?'),
  ('Troppo caro', '뜨로뽀 까로', '너무 비싸요', '쇼핑', null, null, null),
  ('Economico', '에꼬노미꼬', '싸다', '쇼핑', null, null, null),
  ('Felice', '펠리체', '기쁘다', '감정', null, null, null),
  ('Arrabbiato', '아라비아또', '화나다', '감정', null, null, null),
  ('Triste', '뜨리스떼', '슬프다', '감정', null, null, null),
  ('Uno', '우노', '1', '숫자', null, null, null),
  ('Due', '두에', '2', '숫자', null, null, null),
  ('Tre', '뜨레', '3', '숫자', null, null, null),
  ('Oggi', '오찌', '오늘', '시간', null, null, null),
  ('Domani', '도마니', '내일', '시간', null, null, null),
  ('Ieri', '이에리', '어제', '시간', null, null, null),
  ('Scuola', '스꾸올라', '학교', '장소', null, null, null),
  ('Ospedale', '오스뻬달레', '병원', '장소', null, null, null),
  ('Fermata', '페르마따', '정거장', '교통', null, null, null);
